# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy_image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
      - run: docker build . -t app-image

      - name: Run tests in container
      - run: docker run app-image npm run test

      - name: Login to docker hub
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Tag and push image
      - run: docker tag app-image ${{secrets.DOCKER_USERNAME}}/app-image:latest
      - run: docker push ${{secrets.DOCKER_USERNAME}}/app-image:latest
