# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set working directory to ./app
        working-directory: ./app

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
